# Generated by Django 5.2.9 on 2026-01-16 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 17, 18, 8, 38425, tzinfo=datetime.timezone.utc)),
        ),
    ]
