# Generated by Django 5.2.9 on 2026-01-19 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_customuser_data_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 19, 9, 14, 35, 655569, tzinfo=datetime.timezone.utc)),
        ),
    ]
